# permissions for end users to view dbapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: febe-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbapp-viewer-role
rules:
- apiGroups:
  - apps.xiloss.com
  resources:
  - dbapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.xiloss.com
  resources:
  - dbapps/status
  verbs:
  - get
