# permissions for end users to edit dbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: febe-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbservice-editor-role
rules:
- apiGroups:
  - apps.xiloss.com
  resources:
  - dbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.xiloss.com
  resources:
  - dbservices/status
  verbs:
  - get
