---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.xiloss.com
  resources:
  - cloudapps
  - dbservices
  - webapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.xiloss.com
  resources:
  - cloudapps/finalizers
  - dbservices/finalizers
  - webapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.xiloss.com
  resources:
  - cloudapps/status
  - dbservices/status
  - webapps/status
  verbs:
  - get
  - patch
  - update
