apiVersion: apps.xiloss.com/v1alpha1
kind: DbService
metadata:
  labels:
    app.kubernetes.io/name: cloudapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbservice-sample
spec:
  dbServiceStsReplicas: 3
  dbServiceStsImage: mysql:latest
  dbServiceStsExpose: false
  dbServiceSvcPorts:
    - name: mysql
      protocol: TCP
      port: 3306
  dbServiceSvcType: ClusterIP
